name: CI/CD Workflow main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # CI
  cypress-run:
    runs-on: ubuntu-latest
    name: Test with cypress
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cypress install
      uses: cypress-io/github-action@v6
      with:
        build: npm run build
        start: npm run dev

  # CD (VPS)
  deploy:
    needs: cypress-run
    runs-on: ubuntu-latest
    name: Deploy to VPS
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_PRIVATE_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/test_astro
            git pull
            npm install
            npm run build
            systemctl restart nginx