name: CI Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: cypress-io/github-action@v5
      with:
        runTests: false

    - name: Cypress run
      uses: cypress-io/github-action@v5
      continue-on-error: true
      with:
        install: false

    - name: Deploy report to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: cypress/reports/html