name: CI/CD Workflow main
on:
  push:
    branches: [ "main" ]

jobs:
  # CI
  check:
    name: Check astro
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
    
      - name: Astro check
        run: npm run lint:astro


  cypress-run:
    runs-on: ubuntu-latest
    name: Test with cypress
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cypress install
      uses: cypress-io/github-action@v6
      with:
        build: npm run build
        start: npm run dev

  # CD (VPS)
  deploy:
    needs: [ cypress-run, check]
    runs-on: ubuntu-latest
    name: Deploy to VPS
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_PRIVATE_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/test_astro/dist
            git pull
            npm ci
            npm run build