# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# Có 1 thư viện rất nhiều workflows có rất nhiều workflows có sẵn và dc public

name: Node.js CI

#Sự kiện gì sẽ xảy ra để chạy job 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#Định nghĩa các công việc tự động chạy
jobs:

#Tên của 1 job có thể thay đổi bất kì
  build:

#Chạy trên máy ảo
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
